services:
  namenode:
    build:
      context: .
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop-net
    ports:
      - "9870:9870"
      - "8088:8088"
      - "8042:8042"
      - "2222:22"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
      - ./config:/usr/local/hadoop/etc/hadoop
    tty: true
    stdin_open: true

  worker1:
    build:
      context: .
    container_name: worker1
    hostname: worker1
    networks:
      - hadoop-net
    volumes:
      - ./data/worker1:/usr/local/hadoop/hdfs/datanode
      - ./config:/usr/local/hadoop/etc/hadoop
    tty: true
    stdin_open: true

  worker2:
    build:
      context: .
    container_name: worker2
    hostname: worker2
    networks:
      - hadoop-net
    volumes:
      - ./data/worker2:/usr/local/hadoop/hdfs/datanode
      - ./config:/usr/local/hadoop/etc/hadoop
    tty: true
    stdin_open: true

networks:
  hadoop-net:
    external: true